version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: sankshipt-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sankshipt_auth_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - sankshipt-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  auth-server:
    build:
      context: .
      dockerfile: auth-server/Dockerfile
    container_name: sankshipt-auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sankshipt_auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      OAUTH_ISSUER_URI: http://auth-server:9000
    ports:
      - "9000:9000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sankshipt-network

  api-server:
    build:
      context: .
      dockerfile: api-server/Dockerfile
    container_name: sankshipt-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sankshipt_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      OAUTH_ISSUER_URI: http://auth-server:9000
    ports:
      - "8080:8080"
    depends_on:
      - auth-server
    networks:
      - sankshipt-network

volumes:
  mysql_data:

networks:
  sankshipt-network:
    driver: bridge
