spring:
  application:
    name: sankshipt-auth-server

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/sankshipt_auth_db?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      authorization-server:
        issuer: ${OAUTH_ISSUER_URI:http://localhost:9000}

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        web: TRACE
        security: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
