spring:
  application:
    name: Sankshipt

  datasource:
    url: jdbc:h2:mem:sankshiptdb
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true   # enables web console
      path: /h2-console

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: TRACE