spring:
  application:
    name: sankshipt-api

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sankshipt_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: TRACE
        security: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    oauth:
      client-id: sankshipt-client
      client-secret: sankshipt-client-secret
      use-basic-authentication-with-access-code-grant: true
